[TAIPY]
root_folder = "./taipy/"
storage_folder = ".data/"
clean_entities_enabled = "ENV[TAIPY_CLEAN_ENTITIES_ENABLED]"
repository_type = "filesystem"

[JOB]
mode = "development"
max_nb_of_workers = "1:int"

[gui]

[DATA_NODE.default]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"
cacheable = "False:bool"

[DATA_NODE.historical_data]
storage_type = "csv"
scope = "SCENARIO:SCOPE"
cacheable = "False:bool"
default_path = "time_series.csv"
has_header = "True:bool"
exposed_type = "pandas"

[DATA_NODE.month_data]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"
cacheable = "False:bool"

[DATA_NODE.nb_of_values]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"
cacheable = "False:bool"

[TASK.default]
inputs = []
outputs = []

[TASK.filter_current]
inputs = [ "historical_data:SECTION",]
function = "<function filter_current at 0x000002237AA03E20>"
outputs = [ "month_data:SECTION",]

[TASK.count_values]
inputs = [ "month_data:SECTION",]
function = "<function count_values at 0x000002237AF09870>"
outputs = [ "nb_of_values:SECTION",]

[PIPELINE.default]
tasks = []

[PIPELINE.my_pipeline]
tasks = [ "filter_current:SECTION", "count_values:SECTION",]

[SCENARIO.default]
pipelines = []

[SCENARIO.my_scenario]
pipelines = [ "my_pipeline:SECTION",]

[SCENARIO.default.comparators]

[SCENARIO.my_scenario.comparators]
