[TAIPY]
read_entity_retry = "3:int"

[DATA_NODE.input]
default_data = "21:int"

[DATA_NODE.output]

[TASK.double]
function = "__main__.d:function"
inputs = [ "input:SECTION",]
outputs = [ "output:SECTION",]
skippable = "False:bool"

[PIPELINE.my_scenario_pipeline]
tasks = [ "double:SECTION",]

[SCENARIO.my_scenario]
pipelines = [ "my_scenario_pipeline:SECTION",]

[SCENARIO.my_scenario.comparators]
